### ISSUE TITLE
Key error in postrocessing

### ISSUE THREAD

**Issue by EgorBu** [src-d/style-analyzer#328] opened 2018-11-20 00:04 UTC
```
ERROR:662b:EventListener:FAIL ?
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/event_listener.py", line 181, in wrapped_catch_them_all
    return func(self, request, context)
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/event_listener.py", line 202, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/manager.py", line 97, in process_push_event
    model = analyzer.train(ptr, mycfg, self._data_service.get())
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/data_requests.py", line 131, in wrapped_with_uasts_and_contents
    return func(cls, ptr, config, data_request_stub, files=files, **data)
  File "/home/egor/workspace/style-analyzer/lookout/style/format/quality_report.py", line 292, in train
    vnode_parents=vnode_parents, node_parents=node_parents, log=cls.log)
  File "/home/egor/workspace/style-analyzer/lookout/style/format/postprocess.py", line 81, in filter_uast_breaking_preds
    parent = node_parents[id(parent)]
KeyError: 140081885100056
```

**Comment by vmarkovtsev** [comment] 2018-11-20 06:34
@egorbu How to reproduce, what's your environment? Please always include this information in bug reports.

**Comment by EgorBu** [comment] 2018-11-20 09:02
Yes, I will add it soon, @vmarkovtsev.

**Comment by warenlg** [comment] 2018-11-22 05:59
What would help me is the file where you reach this error, so that I can reproduce it. In my case, I met this error only once when processing the whole jquery repo, due to a bblfsh parsing error

**Comment by warenlg** [comment] 2018-11-27 09:35
I believe this is fixed by https://github.com/src-d/style-analyzer/pull/339 and the use of bblfsh proxy https://github.com/src-d/style-analyzer/pull/346
@EgorBu do you still have problems with that ?

**Comment by m09** [comment] 2018-12-04 11:34
@EgorBu is this issue still relevant?

**Comment by warenlg** [comment] 2018-12-07 12:08
@EgorBu ping

**Comment by zurk** [comment] 2018-12-07 16:04
My guess is that this error was found out while Egor created a quality report. 
So right now there is a lot of stuff was reimplemented in PR: https://github.com/src-d/style-analyzer/pull/326 so let's wait until it is merged and a report is created. 

@EgorBu am I right?

**Comment by warenlg** [comment] 2018-12-07 16:45
Above all, this error could no longer occur since https://github.com/src-d/style-analyzer/pull/339, as I said 10 days ago in this issue

**Comment by m09** [comment] 2018-12-07 17:34
Closing, we'll create a new one if needed.

**Closed by m09** 2018-12-07 17:34 UTC
Labels: bug
