### ISSUE TITLE
Improve speed of postprocessing (and probably smoke dataset generation)

### ISSUE THREAD

**Issue by EgorBu** [src-d/style-analyzer#436] opened 2018-12-11 16:32 UTC
Use multiprocessing to check different predictions (that they do not break UAST and don't make different UAST). It should allow reducing duration from hours to minutes using 32 cores at science-3.

**Comment by zurk** [comment] 2018-12-11 17:17
This is a duplicate of https://github.com/src-d/style-analyzer/issues/394
Smoke dataset generation takes 10-20 seconds so let's apply the first rule of optimization.

I would rather close this.

**Comment by zurk** [comment] 2018-12-11 17:41
So do we close it as duplicate? check the mentioned issue.

**Comment by m09** [comment] 2018-12-11 18:23
I'll close because it does seem to be a duplicate of #394. Please re-open if we are mistaken!

**Closed by m09** 2018-12-11 18:23 UTC
Labels: enhancement, format
