### ISSUE TITLE
installing requirements.txt fails with Python 3.7

### ISSUE THREAD

**Issue by smola** [src-d/style-analyzer#175] opened 2018-09-28 10:09 UTC
See https://github.com/snowballstem/pystemmer/issues/18

It seems adding `cython` explicitly to requirements.txt could solve the issue.

cc @zurk

**Comment by zurk** [comment] 2018-09-28 11:46
so, the PR into sourced-ml (https://github.com/src-d/ml/pull/319) should fix installation like
```
pip3 install -r requirements.txt
pip3 install .
```

but the problem is deeper and it is not solving regular installation `pip3 install .` See all details in a related issue: https://github.com/src-d/ml/issues/318

**Comment by vmarkovtsev** [comment] 2018-10-18 08:55
Does it work now @zurk ?

**Comment by zurk** [comment] 2018-10-18 09:34
Yes. You can not just run `pip3 install .`. It fails if you do not have `Cython` installed.
The current workaround is to run 
```
pip3 install -r requirements.txt
pip3 install .
```
or just 
```
pip3 install Cython
pip3 install .
```

**Comment by vmarkovtsev** [comment] 2018-12-10 16:35
This is solved by `install_requires` in src-d/ml.

**Comment by vmarkovtsev** [comment] 2018-12-10 16:36
This is solved by `setup_requires`

**Comment by vmarkovtsev** [comment] 2018-12-10 16:41
Closing this since the original issue is fixed.

**Closed by vmarkovtsev** 2018-12-10 16:41 UTC
