### ISSUE TITLE
Pass the long running tests

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#477] opened 2018-12-14 16:51 UTC
After fixing some bugs, the tests fail at the attribute pruning step returning a `ERROR analysis failed analyzer=test-analyzes app=lookout-sdk error=rpc error: code = DeadlineExceeded desc = Deadline Exceeded provider=`

**Comment by zurk** [comment] 2018-12-15 04:07
Looks like old version of lookout-sdk. App team removed timeout in v0.6.0 and later.
Which version is it?

**Comment by warenlg** [comment] 2018-12-15 19:58
I'm using the latest lookout-sdk v0.6.0

**Comment by warenlg** [comment] 2018-12-17 10:38
This one for example `LONG_TESTS=1 python3 test_analyzer_integration.py` failed after spending too much time on attribute pruning

**Comment by EgorBu** [comment] 2018-12-17 10:49
reproduced the error

**Comment by EgorBu** [comment] 2018-12-17 14:58
```console
/tmp/lookout-sdk-ml-tests/server version
lookout-sdk v0.5.0 built on 11-23-2018_16_43_04
```
Found the problem - I have an old version of server too. Locally it caches the `server` so you need to delete it manually.
@warenlg , could you check it and close the issue?

**Comment by warenlg** [comment] 2018-12-17 16:14
Yes @EgorBu this is a fix ! I'm back testing other files

**Comment by warenlg** [comment] 2018-12-19 15:11
No more errors, with the recent PRs, the long tests passed

**Closed** 2018-12-19 15:38 UTC
